### ISSUE TITLE
 Any expert developer there to support me online for building a html5 app on ripple emulator . Iam struck with some issuue on the ripple

### ISSUE THREAD

**Issue by srk2k13** [blackberry/Ripple-Framework#122] opened 2013-04-15 07:20 UTC
Yes I have tried again by clearing the cache and restarting and a I have also  Uninstalled the ripple and re  installed and it also did'nt solved my problem.

When  I click on the "Riple" Extension
Under Ripple Mssion control when I clicked on the Start  Ripple Services Iam seeing the following error

node.js:205
throw e; // process.nextTick error, or 'error' event on first tick
^
Error: Cannot find module 'delayed-stream'
at Function._resolveFilename (module.js:318:11)
at Function._load (module.js:263:25)
at Module.require (module.js:341:17)
at require (module.js:352:17)
at Object.<anonymous> (C:\Users\Sravan\AppData\Local\Google\Chrome\User Data
\Default\Extensions\cnijnnaimeaacneklcndcafbnkeicckh\0.9.15_0\services\node\node
_modules\ripple-emulator\node_modules\request\node_modules\form-data\node_module
s\combined-stream\lib\combined_stream.js:3:21)
at Module._compile (module.js:416:26)
at Object..js (module.js:434:10)
at Module.load (module.js:335:31)
at Function._load (module.js:294:12)
at Module.require (module.js:341:17)
C:\Program Files\Google\Chrome\Application\26.0.1410.64>

please rectify it and  guide  me where Iam wrong.

**Comment by srk2k13** [comment] 2013-04-15 07:57
when I click on the "Start Riplle services"     a command promp t called "Start B &D" shows with the  follwoing  error

node.js:205
throw e; // process.nextTick error, or 'error' event on first tick
^
Error: Cannot find module 'delayed-stream'
at Function._resolveFilename (module.js:318:11)
at Function._load (module.js:263:25)
at Module.require (module.js:341:17)
at require (module.js:352:17)
at Object.<anonymous> (C:\Users\Sravan\AppData\Local\Google\Chrome\User Data
\Default\Extensions\cnijnnaimeaacneklcndcafbnkeicckh\0.9.15_0\services\node\node
_modules\ripple-emulator\node_modules\request\node_modules\form-data\node_module
s\combined-stream\lib\combined_stream.js:3:21)
at Module._compile (module.js:416:26)
at Object..js (module.js:434:10)
at Module.load (module.js:335:31)
at Function._load (module.js:294:12)
at Module.require (module.js:341:17)
C:\Program Files\Google\Chrome\Application\26.0.1410.64>

Yes Iam seeing the .js called  combined stream and not the delayed stream in thesaid path.

Pls rectify my problem

**Comment by srk2k13** [comment] 2013-04-15 12:09
Now I have uninstalled the google chrome and installed again.

Now when I click on the start"Build and Package"

Iam seeing the following error

Oh Snap! Build request failed with message: CreateProcessW: The system cannot find the file specified.

Starting in production mode.
Picard boldly goes on port 9910...
2013-04-15 12:08:39 POST /ripple/sign/smartphone 200
Checking output path C:/apps/packaged/
Path already exists
Running zip in C:\inetpub\wwwroot\Test
exec - "C:\Users\Sravan\AppData\Local\Google\Chrome\User Data\Default\Extensions
\cnijnnaimeaacneklcndcafbnkeicckh\0.9.14_0\services\node\node_modules\rbd/../../
../bin/zip.exe" -r "C:\apps\packaged/Test.zip" *
error: CreateProcessW: The system cannot find the file specified.

error response - {"code":1,"msg":"CreateProcessW: The system cannot find the fil
e specified.\r\n","data":null}
2013-04-15 12:08:39 GET /ripple/build_status/5388 200

**Comment by cdelcol** [comment] 2013-04-15 13:29
Duplicate of blackberry/Ripple-UI#750

**Closed as completed by cdelcol** 2013-04-15 13:29 UTC
