### ISSUE TITLE
google maps API + Sencha

### ISSUE THREAD

**Issue by noscript** [blackberry/Ripple-Framework#92] opened 2012-01-16 11:35 UTC
Since today I get errors in chrome console when trying to pan/touch the map:

Uncaught TypeError: Cannot read property 'length' of undefined
Nm.(anonymous function).Eb
Q.bindmain.js:21
_raiseTouchEventripple.js:37559
Uncaught TypeError: Object [object Object] has no method 'item'
Om
Nm.(anonymous function).Nb
Q.bindmain.js:21
_raiseTouchEventripple.js:37559

If I disable ripple google maps works fine.

url to test on http://dev.sencha.com/deploy/touch/examples/map/
ripple settings: device iPhone 3G, 3GS; phonegap 1.0

**Comment by dansilivestru** [comment] 2012-01-17 15:47
This has been fixed with this issue: https://github.com/blackberry/Ripple-UI/issues/242 and should be available in the next release.

**Comment by markddavidoff** [comment] 2012-06-13 08:25
I am getting this issue in the latest release.
-caused by a conflict with the ADT extension. Nevermind

**Closed as completed** 2012-06-13 11:25 UTC
Labels: Bug, Staged
